import { Roboto } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";

const roboto = Roboto({ 
  subsets: ["latin"],
  weight:["100", "300", "400", "500", "700", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



import SideBarProvider from "@/components/Contexts/SideBarContext";

import SideBar from "@/components/dashboard/SideBar";
import Header from "@/components/dashboard/Header";

export default async function RootLayout({ children }) {
  
  
  return (
    <html lang="en" className="light">
      <body className={cn("min-h-screen font-sans antialiased grainy",roboto.className) }>
        <SideBarProvider>
          <div className="flex items-start justify-start w-screen h-screen">
              <SideBar/>
              <div className="flex-grow h-full overflow-auto">
                  <Header className="w-full"/>
                  {children}
              </div>
          </div>
        </SideBarProvider>
      </body>
    </html>
  );
}
